### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Abhinav8 Bill",
    "email": "abhinav87_bill@abc.com",
    "address": "gorakhpur",
    "dateOfBirth": "2005-05-05",
    "registeredDate": "2025-05-05"
}

###