### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
    "name": "John Doe4",
    "email": "john.doe22@example.com",
    "address": "222123 Main St, Springfield",
    "dateOfBirth": "1982-06-15"
}
